---
title: "Case Study"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r cars}
library(tidyverse)
library(leaflet)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Load a dataset


```{r pressure, echo=FALSE}
data("nyc_airbnb")
```

* How many rentals are there? Of what type? In what places?
```{r}
nyc_airbnb <- 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location/2) %>% 
  rename(borough = neighbourhood_group)

```
Lets try to count things
```{r}
# make a table
nyc_airbnb %>% 
  count(borough,room_type) %>% 
  pivot_wider(
    names_from = room_type,
    values_from = n
  )
  #janitor::tabyl(borough,room_type)

```

```{r}
ggplot(nyc_airbnb,aes(x=long,y=lat,color=borough))+
  geom_point(size = 0.1)

pal <- colorNumeric(
  palette = "viridis",
  domain = nyc_airbnb$stars)

nyc_airbnb %>% 
  na.omit(stars) %>% 
  mutate(
    click_label = 
      str_c("<b>$", price, "</b><br>", stars, " stars<br>", number_of_reviews, " reviews")) %>% 
  leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(~lat, ~long, radius = .1, color = ~pal(stars), popup = ~click_label)
```

let's lo0k at price and room type
```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price)) +
  geom_point()+
  facet_grid(.~room_type)
```
let's look at price and neighborhood
```{r}
nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  group_by(neighbourhood) %>% 
  summarize(mean_price = mean(price,na.rm =TRUE)) %>% 
  arrange(mean_price)

nyc_airbnb %>% 
  filter(
    borough == "Manhattan",
    price <= 1000) %>% 
  mutate(
    neighbourhood = fct_reorder(neighbourhood,price)
    ) %>% 
  ggplot(aes(x = neighbourhood,y = price))+
  geom_boxplot()+
  coord_flip()+
  facet_grid(.~room_type)
```

获得地铁站的经纬度，结合现有数据，进行爱彼迎公寓距离地铁距离的分析

price vs location
```{r}
nyc_airbnb %>% 
  filter(price<500) %>% 
  sample_n(5000) %>% 
  ggplot(aes(x= lat, y=long,color=price))+
  geom_point(size = 0.1)
```

## retry leaflet
```{r}
pal <- colorNumeric("viridis",NULL)

label <- paste0("<b>", nyc_airbnb$name, "</b><br>$", nyc_airbnb$price)

nyc_airbnb %>% 
  filter(price<500) %>% 
  sample_n(1000) %>% 
  leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(~lat,~long,radius = 1,color = ~pal(price),popup = ~ label)
  
```


